[versions]
analytics = "3.1.2"
assertj = "3.27.3"
changelog = "2.2.1"
checkstyle = "10.15.0"
commons-text = "1.13.1"
flexmark = "0.64.8"
gradle-intellij-plugin-version = "2.6.0"
gson = "2.12.1"
h2 = "2.2.224"
jackson = "2.18.3"
javalin = "5.6.3"
jsoup = "1.19.1"
jtokkit = "1.1.0"
junit = "5.13.4"
kotlin = "2.1.20"
llm-client = "0.8.46"
okio = "3.15.0"
tree-sitter = "0.24.5"
grpc = "1.71.0"
protobuf = "3.25.1"
protobuf-plugin = "0.9.4"

[libraries]
analytics = { module = "com.rudderstack.sdk.java.analytics:analytics", version.ref = "analytics" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
commons-text = { module = "org.apache.commons:commons-text", version.ref = "commons-text" }
flexmark-all = { module = "com.vladsch.flexmark:flexmark-all", version.ref = "flexmark" }
gradle-intellij-plugin = { module = "org.jetbrains.intellij.platform:intellij-platform-gradle-plugin", version.ref = "gradle-intellij-plugin-version" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
jackson-bom = { module = "com.fasterxml.jackson:jackson-bom", version.ref = "jackson" }
javalin = { module = "io.javalin:javalin", version.ref = "javalin" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
jtokkit = { module = "com.knuddels:jtokkit", version.ref = "jtokkit" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
llm-client = { module = "ee.carlrobert:llm-client", version.ref = "llm-client" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
tree-sitter = { module = "io.github.bonede:tree-sitter", version.ref = "tree-sitter" }
grpc-protobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpc" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpc" }
grpc-netty-shaded = { module = "io.grpc:grpc-netty-shaded", version.ref = "grpc" }
protobuf-protoc = { module = "com.google.protobuf:protoc", version.ref = "protobuf" }
protobuf-java = { module = "io.grpc:protoc-gen-grpc-java", version.ref = "grpc" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
protobuf = { id = "com.google.protobuf", version.ref = "protobuf-plugin" }
